// lib/data.js
// Why this file exists: single source of sample data for the whole front-end.
// No backend yet — pages import from here so the site is fully navigable with
// realistic Bangladesh-market content (prices in BDT, new/used, official/unofficial).

export const SITE = {
  name: "Apple Network",
  tagline: "বাংলাদেশের বিশ্বস্ত ফোন ও ইলেকট্রনিক্স স্টোর",
  phone: "০৯৬১২-৩৪৫৬৭৮",
  email: "hello@apple-network.bd",
  supportEmail: "support@apple-network.bd",
  address: "লেভেল ৭, ব্লক বি, বসুন্ধরা সিটি, ঢাকা",
  hours: "প্রতিদিন সকাল ১০টা – রাত ৮টা",
  builder: "XafLab",
};

// Main store categories (customer-facing). `icon` = lucide-react icon name.
export const CATEGORIES = [
  { slug: "phones", name: "মোবাইল ফোন", en: "Phones", icon: "Smartphone", desc: "নতুন ও পুরানো, অফিশিয়াল ও আনঅফিশিয়াল" },
  { slug: "accessories", name: "অ্যাক্সেসরিজ", en: "Accessories", icon: "Headphones", desc: "কেস, চার্জার, ইয়ারবাডস, পাওয়ার ব্যাংক" },
  { slug: "laptops", name: "ল্যাপটপ ও ট্যাবলেট", en: "Laptops & Tablets", icon: "Laptop", desc: "নতুন ও রিফার্বিশড" },
  { slug: "watches", name: "স্মার্টওয়াচ", en: "Smart Watches", icon: "Watch", desc: "ফিটনেস ও স্মার্ট ব্যান্ড" },
  { slug: "tv-audio", name: "স্মার্ট টিভি ও অডিও", en: "Smart TV & Audio", icon: "Tv", desc: "টিভি, সাউন্ডবার, স্পিকার" },
  { slug: "gadgets", name: "গ্যাজেটস", en: "Gadgets", icon: "Cpu", desc: "স্মার্ট হোম, গেমিং, আরও" },
];

// Brand list for phone filters
export const BRANDS = ["iPhone", "Samsung", "Xiaomi", "OPPO", "vivo", "Realme", "OnePlus", "Nokia", "Honor", "Motorola"];

export const CONDITIONS = [
  { key: "new-official", label: "নতুন (অফিশিয়াল)" },
  { key: "new-unofficial", label: "নতুন (আনঅফিশিয়াল)" },
  { key: "used-excellent", label: "প্রিলাভড — Excellent" },
  { key: "used-good", label: "প্রিলাভড — Good" },
];

// helper to format BDT with Bangla numerals
const bn = (n) => (n ?? 0).toLocaleString("bn-BD");
export const taka = (n) => `৳${bn(n)}`;

// Sample product catalog. Prices in BDT. `condition` and `official` drive filters.
export const PRODUCTS = [
  {
    slug: "samsung-galaxy-a24",
    name: "Samsung Galaxy A24",
    brand: "Samsung",
    category: "phones",
    condition: "new-official",
    official: true,
    price: 22900,
    regularPrice: 26490,
    storage: "128GB",
    ram: "6GB",
    color: "কালো",
    badge: "hot",
    emiFrom: 1910,
    inStock: true,
    rating: 4.5,
    reviews: 128,
    image: "/images/products/samsung.png",
    specs: {
      "ডিসপ্লে": "৬.৫ ইঞ্চি Super AMOLED, ৯০Hz",
      "প্রসেসর": "MediaTek Helio G99",
      "RAM": "6GB",
      "স্টোরেজ": "128GB (microSD সাপোর্ট)",
      "ক্যামেরা": "50MP + 5MP + 2MP",
      "ফ্রন্ট ক্যামেরা": "13MP",
      "ব্যাটারি": "5000mAh, 25W ফাস্ট চার্জিং",
      "OS": "Android (One UI)",
    },
    desc: "বাজেটের মধ্যে নির্ভরযোগ্য ডেইলি-ড্রাইভার। উজ্জ্বল AMOLED ডিসপ্লে, বড় ব্যাটারি ও ভালো ক্যামেরা।",
  },
  {
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "iPhone",
    category: "phones",
    condition: "new-official",
    official: true,
    price: 114900,
    regularPrice: 124900,
    storage: "128GB",
    ram: "6GB",
    color: "ব্লু",
    badge: "choice",
    emiFrom: 9575,
    inStock: true,
    rating: 4.8,
    reviews: 342,
    image: "/images/products/iphone.png",
    specs: {
      "ডিসপ্লে": "৬.১ ইঞ্চি Super Retina XDR",
      "চিপ": "A16 Bionic",
      "স্টোরেজ": "128GB",
      "ক্যামেরা": "48MP মেইন + 12MP আল্ট্রা-ওয়াইড",
      "ব্যাটারি": "সারাদিন ব্যাকআপ",
      "OS": "iOS 17",
    },
    desc: "Dynamic Island, 48MP ক্যামেরা এবং USB-C সহ আসল অফিশিয়াল iPhone 15 — ওয়ারেন্টিসহ।",
  },
  {
    slug: "iphone-13-used",
    name: "iPhone 13 (প্রিলাভড)",
    brand: "iPhone",
    category: "phones",
    condition: "used-excellent",
    official: false,
    price: 62900,
    regularPrice: 78000,
    storage: "128GB",
    ram: "4GB",
    color: "মিডনাইট",
    badge: "excellent",
    emiFrom: 5240,
    inStock: true,
    rating: 4.6,
    reviews: 89,
    image: "/images/products/iphone.png",
    specs: {
      "ডিসপ্লে": "৬.১ ইঞ্চি Super Retina XDR",
      "চিপ": "A15 Bionic",
      "স্টোরেজ": "128GB",
      "ব্যাটারি হেলথ": "৮৯% (যাচাই করা)",
      "কন্ডিশন": "Excellent — প্রায় নতুনের মতো",
      "ওয়ারেন্টি": "৩০ দিন সেলার ওয়ারেন্টি",
    },
    desc: "যাচাই করা প্রিলাভড iPhone 13 — Excellent গ্রেড, ৮৯% ব্যাটারি হেলথ। কম দামে ভালো ফোন।",
  },
  {
    slug: "xiaomi-redmi-note-13",
    name: "Xiaomi Redmi Note 13",
    brand: "Xiaomi",
    category: "phones",
    condition: "new-official",
    official: true,
    price: 24999,
    regularPrice: 27999,
    storage: "256GB",
    ram: "8GB",
    color: "গ্রিন",
    badge: "top",
    emiFrom: 2083,
    inStock: true,
    rating: 4.4,
    reviews: 210,
    image: "/images/products/samsung.png",
    specs: {
      "ডিসপ্লে": "৬.৬৭ ইঞ্চি AMOLED, ১২০Hz",
      "প্রসেসর": "Snapdragon 685",
      "RAM": "8GB",
      "স্টোরেজ": "256GB",
      "ক্যামেরা": "108MP মেইন",
      "ব্যাটারি": "5000mAh, 33W",
      "OS": "Android (MIUI)",
    },
    desc: "108MP ক্যামেরা, 120Hz AMOLED ডিসপ্লে ও বড় স্টোরেজ — দামের তুলনায় দুর্দান্ত ভ্যালু।",
  },
  {
    slug: "vivo-y300t",
    name: "vivo Y300t",
    brand: "vivo",
    category: "phones",
    condition: "new-unofficial",
    official: false,
    price: 19888,
    regularPrice: 22500,
    storage: "128GB",
    ram: "8GB",
    color: "সিলভার",
    badge: "demand",
    emiFrom: 1657,
    inStock: true,
    rating: 4.2,
    reviews: 54,
    image: "/images/products/samsung.png",
    specs: {
      "ডিসপ্লে": "৬.৭২ ইঞ্চি, ১২০Hz",
      "প্রসেসর": "Snapdragon 4 Gen 2",
      "RAM": "8GB",
      "স্টোরেজ": "128GB",
      "ব্যাটারি": "6000mAh",
      "কন্ডিশন": "নতুন (আনঅফিশিয়াল)",
    },
    desc: "বিশাল 6000mAh ব্যাটারি ও 120Hz ডিসপ্লে — আনঅফিশিয়াল, তাই দামে সাশ্রয়ী।",
  },
  {
    slug: "oneplus-ace-6",
    name: "OnePlus Ace 6",
    brand: "OnePlus",
    category: "phones",
    condition: "new-official",
    official: true,
    price: 54990,
    regularPrice: 59990,
    storage: "256GB",
    ram: "12GB",
    color: "কালো",
    badge: "hot",
    emiFrom: 4583,
    inStock: false,
    rating: 4.7,
    reviews: 76,
    image: "/images/products/samsung.png",
    specs: {
      "ডিসপ্লে": "৬.৮ ইঞ্চি AMOLED, ১৪৪Hz",
      "প্রসেসর": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "স্টোরেজ": "256GB",
      "ব্যাটারি": "6000mAh, 100W",
      "OS": "Android (OxygenOS)",
    },
    desc: "ফ্ল্যাগশিপ পারফরম্যান্স — Snapdragon 8 Gen 3, 144Hz ডিসপ্লে, 100W চার্জিং।",
  },
  // Accessories
  {
    slug: "tempered-glass-universal",
    name: "টেম্পারড গ্লাস স্ক্রিন প্রোটেক্টর",
    brand: "Apple Network",
    category: "accessories",
    condition: "new-official",
    official: true,
    price: 250,
    regularPrice: 400,
    badge: "top",
    inStock: true,
    rating: 4.3,
    reviews: 512,
    image: "/images/products/charger.png",
    specs: { "টাইপ": "9D টেম্পারড গ্লাস", "ফিটিং": "ইন-স্টোর ইনস্টলেশন সুবিধা", "ওয়ারেন্টি": "রিপ্লেসমেন্ট গ্যারান্টি" },
    desc: "9D ফুল-কভারেজ টেম্পারড গ্লাস। ইন-স্টোর ফিটিং সুবিধাসহ।",
  },
  {
    slug: "20w-fast-charger",
    name: "20W ফাস্ট চার্জার (USB-C)",
    brand: "Apple Network",
    category: "accessories",
    condition: "new-official",
    official: true,
    price: 890,
    regularPrice: 1200,
    inStock: true,
    rating: 4.5,
    reviews: 231,
    image: "/images/products/charger.png",
    specs: { "আউটপুট": "20W USB-C PD", "কম্প্যাটিবল": "iPhone ও Android", "ওয়ারেন্টি": "৬ মাস" },
    desc: "দ্রুত ও নিরাপদ চার্জিং — iPhone ও Android উভয়ের জন্য।",
  },
  {
    slug: "wireless-earbuds-tws",
    name: "ওয়্যারলেস ইয়ারবাডস (TWS)",
    brand: "Apple Network",
    category: "accessories",
    condition: "new-official",
    official: true,
    price: 1490,
    regularPrice: 2200,
    badge: "choice",
    inStock: true,
    rating: 4.4,
    reviews: 178,
    image: "/images/products/earbuds.png",
    specs: { "টাইপ": "TWS ব্লুটুথ ৫.৩", "ব্যাকআপ": "২৪ ঘণ্টা (কেসসহ)", "ফিচার": "নয়েজ রিডাকশন" },
    desc: "ক্লিয়ার সাউন্ড, লম্বা ব্যাকআপ ও নয়েজ রিডাকশন — বাজেট প্রাইসে।",
  },
  {
    slug: "power-bank-20000",
    name: "পাওয়ার ব্যাংক ২০,০০০mAh",
    brand: "Apple Network",
    category: "accessories",
    condition: "new-official",
    official: true,
    price: 1990,
    regularPrice: 2800,
    inStock: true,
    rating: 4.6,
    reviews: 143,
    image: "/images/products/powerbank.png",
    specs: { "ক্যাপাসিটি": "20000mAh", "আউটপুট": "22.5W ফাস্ট চার্জিং", "পোর্ট": "USB-C + দুটি USB-A" },
    desc: "ভ্রমণের সঙ্গী — একসাথে একাধিক ডিভাইস চার্জ করুন।",
  },
  {
    slug: "apple-watch-se-used",
    name: "Apple Watch SE (প্রিলাভড)",
    brand: "Apple",
    category: "watches",
    condition: "used-good",
    official: false,
    price: 18900,
    regularPrice: 24000,
    badge: "good",
    inStock: true,
    rating: 4.3,
    reviews: 41,
    image: "/images/products/smartwatch.png",
    specs: { "সাইজ": "40mm", "কন্ডিশন": "Good — হালকা ব্যবহারের চিহ্ন", "ওয়ারেন্টি": "১৫ দিন সেলার ওয়ারেন্টি" },
    desc: "যাচাই করা প্রিলাভড Apple Watch SE — Good গ্রেড, দামে সাশ্রয়ী।",
  },
  {
    slug: "smart-tv-43",
    name: "৪৩ ইঞ্চি স্মার্ট টিভি",
    brand: "Xiaomi",
    category: "tv-audio",
    condition: "new-official",
    official: true,
    price: 32900,
    regularPrice: 38000,
    badge: "hot",
    inStock: true,
    rating: 4.5,
    reviews: 67,
    image: "/images/products/samsung.png",
    specs: { "সাইজ": "৪৩ ইঞ্চি", "রেজোলিউশন": "Full HD / 4K", "OS": "Android TV", "স্ট্রিমিং": "YouTube, Netflix" },
    desc: "স্মার্ট স্ট্রিমিং টিভি — YouTube, Netflix বিল্ট-ইন। ফ্রি ডেলিভারি ও ইনস্টলেশন।",
  },
];

// Blog posts (from content file)
export const BLOG_POSTS = [
  { slug: "buy-used-phone-safely", title: "স্ক্যাম ছাড়াই বাংলাদেশে পুরানো ফোন কেনার উপায়", cat: "গাইড", excerpt: "শারীরিক পরিদর্শন, ব্যাটারি হেলথ, IMEI চেক ও রেড ফ্ল্যাগ — নিরাপদে প্রিলাভড ফোন কিনুন।", read: "৬ মিনিট" },
  { slug: "emi-vs-cash", title: "EMI নাকি ক্যাশ — ফোন কেনার সময় কোনটা ভালো?", cat: "টিপস", excerpt: "ইন্সটলমেন্ট বনাম ক্যাশ, ২৪+ ব্যাংক অপশন, মোট খরচ — কখন EMI স্মার্ট চয়েস।", read: "৫ মিনিট" },
  { slug: "exchange-old-phone", title: "পুরানো ফোন এক্সচেঞ্জ করে নতুনটার দাম কমান", cat: "গাইড", excerpt: "এক্সচেঞ্জ ভ্যালু কীভাবে নির্ধারিত হয় ও সর্বোচ্চ ভ্যালু পাওয়ার টিপস।", read: "৪ মিনিট" },
  { slug: "official-vs-unofficial", title: "অফিশিয়াল বনাম আনঅফিশিয়াল ফোন — আসল পার্থক্য কী?", cat: "গাইড", excerpt: "ওয়ারেন্টি, প্যাকেজিং, আমদানি সোর্স ও দাম — কোনটা কার জন্য।", read: "৫ মিনিট" },
  { slug: "best-phones-under-20k", title: "২০,০০০ টাকার নিচে সেরা মোবাইল ফোন (২০২৬ গাইড)", cat: "রিভিউ", excerpt: "নতুন ও নির্ভরযোগ্য প্রিলাভড অপশনের তুলনা — ব্যাটারি, ক্যামেরা, পারফরম্যান্স।", read: "৭ মিনিট" },
  { slug: "phone-battery-health", title: "ফোনের ব্যাটারি সুস্থ রাখার সহজ টিপস", cat: "টিপস", excerpt: "সঠিক চার্জিং অভ্যাস, গরম এড়ানো ও সেটিংস — ব্যাটারি লাইফ বাড়ান।", read: "৪ মিনিট" },
];

// convenience lookups
export const getProduct = (slug) => PRODUCTS.find((p) => p.slug === slug);
export const byCategory = (cat) => PRODUCTS.filter((p) => p.category === cat);
export const phones = () => byCategory("phones");
export const featured = () => PRODUCTS.filter((p) => p.badge).slice(0, 8);
