// lib/orders.js
// Why: create a real order in Supabase from the client cart (guest session).
// Uses the browser anon client; RLS policies allow guest inserts keyed by session_id.

"use client";

import { createClient } from "@supabase/supabase-js";
import { getSessionId } from "@/lib/cart";

function sb() {
  const url = process.env.NEXT_SUPABASE_URL;
  const key = process.env.NEXT_SUPABASE_ANON_KEY;
  if (!url || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

function mapCondition(ui) {
  if (!ui) return null;
  if (ui.includes("অফিশিয়াল")) return "new_official";
  if (ui.includes("Good") || ui.includes("গুড")) return "used_good";
  if (ui.includes("Excellent") || ui.includes("এক্সেলেন্ট")) return "used_excellent";
  if (ui.includes("আনঅফিশিয়াল")) return "new_unofficial";
  return "new_official";
}

// items: [{ slug, name, price, image, color, storage, ram, condition, qty }]
// shipping: { name, phone, email, address, city, division, notes }
// payment: "cod" | "bkash" | "nagad" | "card" | "emi"
export async function createOrder({ items, shipping, payment }) {
  const client = sb();
  if (!client) throw new Error("Supabase not configured");

  const subtotal = items.reduce((s, i) => s + i.price * i.qty, 0);
  const shippingCost = 0; // free delivery
  const total = subtotal + shippingCost;
  const sessionId = getSessionId();

  // 1) insert order (order_number auto-generated by DB trigger)
  const { data: order, error: oe } = await client
    .from("orders")
    .insert({
      session_id: sessionId,
      status: "confirmed",
      subtotal_bdt: subtotal,
      shipping_bdt: shippingCost,
      discount_bdt: 0,
      total_bdt: total,
      payment_method: payment,
      payment_status: payment === "cod" ? "pending" : "pending",
      shipping_name: shipping.name,
      shipping_phone: shipping.phone,
      shipping_email: shipping.email || null,
      shipping_address: shipping.address,
      shipping_city: shipping.city,
      shipping_division: shipping.division,
      shipping_notes: shipping.notes || null,
    })
    .select("id, order_number")
    .single();
  if (oe) throw oe;

  // 2) insert order items (snapshot name/image/variant). condition mapped to DB enum.
  const rows = items.map((i) => ({
    order_id: order.id,
    product_id: null,
    product_name: i.name,
    product_image: i.image,
    color: i.color || null,
    storage: i.storage || null,
    ram: i.ram || null,
    condition: mapCondition(i.condition),
    unit_price_bdt: i.price,
    qty: i.qty,
    line_total_bdt: i.price * i.qty,
  }));
  const { error: ie } = await client.from("order_items").insert(rows);
  if (ie) throw ie;

  return { orderId: order.id, orderNumber: order.order_number, total };
}

// Look up an order by its AN- number (for tracking). Reads public-ish data via RLS.
export async function getOrderByNumber(orderNumber) {
  const client = sb();
  if (!client) return null;
  const { data, error } = await client
    .from("orders")
    .select("id, order_number, status, total_bdt, payment_method, payment_status, shipping_name, created_at, order_items(id, product_name, product_image, qty, unit_price_bdt, color, storage, ram)")
    .eq("order_number", orderNumber.trim().toUpperCase())
    .maybeSingle();
  if (error) return null;
  return data;
}
